version: "3.8"

services:
  productdb:
    image: mysql:8.0.30
    networks:
    - default

  portainer:
    image: portainer/portainer-ce
    networks:
      - default

  product.api:
    image: ${DOCKER_REGISTRY-}product-api:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: .
      dockerfile: Services/Product.API/Dockerfile
    networks:
      - default

#network section
networks:
  default:
    name: aspnet
    driver: bridge

#volumes section
volumes:
  mysql_data:
    name: mysql_data

  portainer_data:
    name: portainer_data
