version: '3.8'

services:
  productdb:
    container_name: productdb
    environment:
      MYSQL_ROOT_PASSWORD: Trungnam.123
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"
  
  customerdb:
    container_name: customerdb
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD=Trungnam.123
      - POSTGRES_DB=CustomerDb
    restart: always
    ports:
        - "5433:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
  
  basketdb: 
    container_name: basketdb
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "Trungnam.123"
        ACCEPT_EULA: "Y"
    restart: always
    volumes:
        - sqlserver_data:/var/lib/sqlserver/data
    ports:
        - "1435:1433"
  
  inventorydb: 
    container_name: inventorydb
    restart: always
    ports:
        - "27018:27017"
    volumes:
        - mongo_data:/data/db
  
  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnection=Server=productdb;Port=3306;Database=ProductDb;Uid=root;Pwd=Trungnam.123;"
    restart: always
    depends_on:
      - productdb
    ports:
      - "6002:80"
  
  customer.api:
    container_name: customer.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnection=Server=customerdb;Port=5432;Database=CustomerDb;User Id=postgres;Password=Trungnam.123;"
    restart: always
    depends_on:
      - customerdb
    ports:
      - "6003:80"
  
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "GrpcSettings:StockUrl=http://inventory.grpc"
    restart: always
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "6004:80"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnectionString=Server=orderdb;Database=OrderDb;User=sa;Password=Trungnam.123;MultipleActiveResultSets=True"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    restart: always
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "6005:80"

  inventory.api:
    container_name: inventory.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "MongoDbDatabaseSettings:ConnectionString=mongodb://inventorydb:27017"
      - "MongoDbDatabaseSettings:DatabaseName=InventoryDb"
    restart: always
    depends_on:
      - inventorydb
    ports:
      - "6006:80"

  inventory.grpc:
    container_name: inventory.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "MongoDbDatabaseSettings:ConnectionString=mongodb://inventorydb:27017"
      - "MongoDbDatabaseSettings:DatabaseName=InventoryDb"
    restart: always
    depends_on:
      - inventorydb
    ports:
      - "6007:80"
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=thtntrungnam@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Trungnam.123
    restart: always
    ports:
        - "5050:80"
    volumes:
        - pgadmin_data:/root/.pgadmin
  
  rabbitmq: 
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"
    