version: "3.8"

services:
  productdb:
    image: mysql:8.0.30
  
  customerdb:
    image: postgres:alpine3.16
  
  basketdb:
    image: redis:alpine
  
  inventorydb:
    image: mongo
  
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  portainer:
    image: portainer/portainer-ce

  pgadmin:
    image: dpage/pgadmin4
  
  rabbitmq:
    image: rabbitmq:3-management-alpine

  product.api:
    image: ${DOCKER_REGISTRY-}product-api:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: .
      dockerfile: Services/Product.API/Dockerfile

  customer.api:
    image: ${DOCKER_REGISTRY-}customer-api:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: .
      dockerfile: Services/Customer.API/Dockerfile
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basket-api:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: .
      dockerfile: Services/Basket.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}ordering-api:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  inventory.api:
    image: ${DOCKER_REGISTRY-}inventory-api:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: .
      dockerfile: Services/Inventory/Inventory.API/Dockerfile

  inventory.grpc:
    image: ${DOCKER_REGISTRY-}inventory-grpc:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: .
      dockerfile: Services/Inventory/Inventory_gRPC/Dockerfile

#network section
networks:
  default:
    name: aspnet
    driver: bridge

#volumes section
volumes:
  mysql_data:
    name: mysql_data

  portainer_data:
    name: portainer_data
  
  postgres_data:
    name: postgres_data

  pgadmin_data:
    name: pgadmin_data

  redis_data:
    name: redis_data

  sqlserver_data:
    name: sqlserver_data

  mongo_data:
    name: mongo_data